# Site settings
title: 三文鱼
email: fxmmc@sina.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hanmbink.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  hanmbink

# Build settings
markdown: kramdown
